from playwright.sync_api import expect, Page


def test_sub(page: Page):
    page.goto("https://www.qa-practice.com/forms/practice-form")
    expect(page).to_have_url("https://www.qa-practice.com/forms/practice-form")
    page.get_by_role("textbox", name="First Name").fill("jgh")
    expect(page.get_by_placeholder("First Name")).to_have_value("jgh")
    page.get_by_role("textbox", name="Last Name").fill("las")
    expect(page.get_by_placeholder("Last Name")).to_have_value("las")
    page.get_by_role("textbox", name="Email").fill("set89@inbox.ru")
    expect(page.get_by_placeholder("name@example.com")).to_have_value("set89@inbox.ru")
    page.locator("#gender_0").click()
    expect(page.locator("#gender_0")).to_be_enabled()
    page.get_by_role("textbox", name="Mobile").fill("8963111155")
    expect(page.get_by_placeholder("Mobile Number")).to_have_value("8963111155")
    page.get_by_role("textbox", name="Date of Birth").fill("2026-7-3")
    expect(page.get_by_role("textbox", name="Date of Birth")).to_have_value("2026-7-3")
    page.get_by_role("textbox", name="Subjects").fill("Maths")
    page.locator(".suggestion-item").click()
    expect(page.locator("#subjectsInput")).to_have_value("Maths")
    page.locator("#hobbies_0").click()
    expect(page.locator("#hobbies_0")).to_be_enabled()
    page.get_by_role("textbox", name="Current Address").fill("USSR")
    expect(page.get_by_placeholder("Current Address")).to_have_value("USSR")
    page.locator("//span[text()='Select State']").click()
    page.locator("[data-value='NCR']").click()
    expect(page.locator("//span[text()='NCR']")).to_have_text("NCR")
    page.locator("//span[text()='Select City']").click()
    page.locator("[data-value='Delhi']").click()
    expect(page.locator("//span[text()='Delhi']")).to_have_text("Delhi")
    page.locator("#submit-id-submit").click()
    expect(page.locator("//div[@class='modal-content']")).to_be_visible()
